spring.application.name=allocation-service

server.port=8082

# sqlite database
spring.datasource.url=jdbc:sqlite:allocation.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# jpa / hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# useful during development
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# customer service
customer.service.url=${CUSTOMER_SERVICE_URL:http://localhost:8081}


# taro service
taro.service.url=${TARO_SERVICE_URL:http://localhost:8083}
