spring.application.name=taro-service

server.port=8083

# sqlite database
spring.datasource.url=jdbc:sqlite:taro.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# jpa / hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# useful during development
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false